Diatonic and non-diatonic scales, Key module
battermann/Tonal pull request #25
Opened 2018-10-07 06:24 UTC by duncanmalashock

2018-10-10 20:23 UTC, battermann requested changes
So far I only review the Key module.

2018-10-10 20:23 UTC, battermann commented on src/MusicTheory/Key.elm
> +module Key exposing
This module looks quite nice.

We could provide functions that return the corresponding/relative minor to a major key and vice versa.

2018-10-10 20:23 UTC, battermann commented on src/MusicTheory/Key.elm
> +module Key exposing
The module name should be `MusicTheory.Key`.

2018-10-10 20:23 UTC, battermann commented on src/MusicTheory/Key.elm
> +type Tonality
I don't think this is the right name. Tonality involves a tonic but this just specifies if it's minor or major.

We could call this `KeyClass` or `KeyQuality`.

2018-10-10 20:23 UTC, battermann commented on src/MusicTheory/Key.elm
> +scaleDegrees : Key -> DiatonicScaleDegrees
I think it's good that the codomain restricted to `DiatonicScaleDegrees`.

But ATM there is no way to make either a list or a `ScaleClass` out of this (at least I didn't find a way). There should be some way to do this.

2018-10-12 03:25 UTC, duncanmalashock commented
After discussing with @battermann I agree that this implementation is too complicated. Closing.

2018-10-12 03:25 UTC, closed without merging